backend:
  name: git-gateway
  branch: main

media_folder: /assets
public_folder: ../assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: posts
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: string }
      - { name: heroImagePath, label: Hero Image Path, default: ../assets/blank.png }
      - { name: authors, label: Authors, widget: list }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
