backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{slug}}'
    update: 'Update {{slug}}'
    delete: 'Delete {{slug}}'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'


media_folder: /assets
public_folder: ../assets
publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: posts
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: string }
      - { name: heroImage, label: Hero Image Path, default: ../assets/ }
      - { name: authors, label: Authors, widget: list }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
